name: C++ CI Pipeline

# 1. When should this pipeline run?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Grant GitHub Actions permission to push to your GitHub Pages website
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    # 2. Operating system for CI server to use
    runs-on: ubuntu-latest

    steps:
    # 3. Download repository's code onto the CI server
    - name: Checkout code
      uses: actions/checkout@v4

    # 4. Configure CMake (Turn ON the tests explicitly)
    - name: Configure CMake
      run: cmake -B build -S . -DDATASTRUCTS_BUILD_TESTS=ON -DDATASTRUCTS_BUILD_EXAMPLES=ON

    # 5. Compile the library, examples, and GoogleTests
    - name: Build Project
      run: cmake --build build

    # 6. Run CTest to execute all test executables
    - name: Run Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure

    # --- NEW JOB: Generate and Deploy Documentation ---
  deploy-docs:
    # Only run this job if the build-and-test job passes successfully
    needs: build-and-test
    runs-on: ubuntu-latest
    # Only deploy when pushing to main (don't deploy on pull requests)
    if: github.ref == 'refs/heads/main'

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Doxygen & Graphviz
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Generate Documentation
      run: cmake --build build --target docs

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # This is where Doxygen generated the HTML site
        path: './html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
